team-bofit/bofit-client

apps/client/package.json
apps/client/src/shared/api/config/instance.ts
pnpm-lock.yaml

- #12
- ky ?
- fetch API를 더 쉽고 간결하게 사용할 수 있도록 만든 경량 HTTP 클라이언트 라이브러리
- Promise 기반의 직관적인 문법으로 GET/POST 등 HTTP 요청을 쉽게 작성
- .json() 메서드로 응답을 바로 JSON 데이터로 변환
- 에러 처리, retry, timeout, hooks(요청 전/후 커스텀 로직) 등 내장 기능 지원
- axios보다 가볍고, 최신 브라우저/Node.js 환경에서 더욱 최적화
- ky 라이브러리로 기본 API 인스턴스(kyinstance) 생성
- prefixUrl은 환경 변수 VITE_BASE_URL로 설정 (`.env`에 작성)
- 기본 헤더는 JSON 통신을 위한 Content-Type 설정만 적용
- timeout, hooks 등은 추후 API 나온 후 추가해야 함
- 예시용 API 호출 함수 `getPost` 및 tanstack query 기반 `usePostQuery` 훅 pr에 작성
- 테스트로 jsonplaceholder의 `posts/2` 호출
- 서버 API 명세 및 응답이 아직 확정 전이라, 최소 세팅 및 동작 확인 목적
예시 코드
```ts
// app/client/.env
VITE_BASE_URL=https://jsonplaceholder.typicode.com
```
```ts
import ky from 'ky';
export const kyinstance = ky.create({
// 모든 요청의 prefix로 사용할 base URL
prefixUrl: import.meta.env.VITE_BASE_URL, …
```

Init(client): ky 세팅

---

apps/client/src/shared/hooks/use-input-state.ts

- #19 
- useInputState 커스텀 훅 추가
크게는 커뮤니티 기능에 필수적으로 사용하게 될 inputState 를 선언적으로 관리하기 위해서 useInputState 를 구현했습니다.
해당 훅의 역할을 입력 폼의 상태를 간단하고 선언적으로 처리하기 위함이라고 생각하시면 될 것 같아요
보통은 input의 요소 value 와 onChange 를 별도의 컴포넌트에서 직접 관리하게 되는데,  이 부분의 번거로움과 중복 코드를 줄여줘요
그리고 사용자가 입력한 값을 필요에 따라 변환할 수 있는 transformValue 라는 선택적 함수도 제공하고 있어요. 
initialValue : 입력 상태의 초기값을 선택할 수 있어요. 기본 값은 빈 문자열이지만, 설정해두면 입력폼의 초기값을 설정할 수 있습니다. 
`transformValue` : 는 입력값을 변경할 때 마다 호출되는 변환 함수에요, 기본 값은 echo 함수로 설정되어 있어서 기본적으로는 입력 받은 값을 그대로 반환하지만, 
공백을 제거하거나, 소문자/ 대문자 변환, 숫자만 허용하는 등의 용도로 사용할 수 있어요 
```tsx
const [value, onChange] = useInputState('', (v) => v.trim());
```
이런식으로요 !
자세한 내용은 tsdoc 형태로 작성해두었어요.
코드 재사용성도 증가하고, 가독성도 향상되기에 이 훅을 미리 추가해두었습니다 ㅎㅎ
```tsx
import { useState, ChangeEvent } from 'react';
function Example() {
const [value, …
```

Feat(client): useInputState 커스텀 훅 추가

---

apps/client/src/shared/components/switch-case.tsx

- #21 
- switch-case 컴포넌트 구현
해당 컴포넌트의 가장 큰 장점은 조건부 렌더링 로직을 선언적으로 변경해준다는 것에 있어요 
기존에는 우선 jsx 바깥에서 제어문으로 분기처리를 했었는데, switchCase 컴포넌트를 사용하면 분기 로직이 객체 형태로 일대일 대칭이 이루어지면서 어떤 조건에 어떤 UI가 렌더링 될지 한 눈에 파악가능하다는 장점이 있어요 
유지보수 할 때에도 value 혹은 caseBy만 바꿔주면 되기에 렌더링 로직을 추가로 변경하지 않아도 된다는 장점두 있구용
간단한 조건부 렌더링의 경우에는 삼항 연산자를 쓰는 것이 더 효율적이지만, 2개 이상의 case가 생길 경우 사용하면 좋을 것 같습니다
```tsx
* <SwitchCase
*   value={true}
*   caseBy={{
*     true: () => <div>참입니다</div>,
*     false: () => <div>거짓입니다</div>,
*   }}
*   defaultComponent={() => <div>일치하는 값이 없습니다</div>}
* />
```

Feat(client): SwitchCase 컴포넌트 구현

---

.github/workflows/discord-notify.yml

- #27 
디스코드에 PR 생성 시, 병합 시에 알림을 주기 위해서
.github/workflow/discord-notify.yml 파일 생성하고 작성했습니다.
- 레포지토리에 new secret 생성했습니다.
- .github/workflow/discord-notify.yml 파일 생성하고 작성했습니다.
이제 PR 생성 및, 병합 시에 디스코드 WEB채널 🎱깃허브-noti 채널에 알림전송됩니다. 추가적으로 필요한 이벤트 트리거 있으면 말씀해주세요
올바른 코드리뷰 문화의 정착을 위해....👧

Chore: discord 알림 .yml 파일 생성

---

packages/bds-ui/src/components/chip/chip.stories.tsx

Chore(bds): Chip 컴포넌트 주석 제거

---

apps/client/src/widgets/onboarding/components/title/title.css.ts
apps/client/src/widgets/onboarding/components/title/title.tsx

- #126 
정보 입력 4가지 step에 모두 같은 타이틀이 사용되어서 컴포넌트로 구현했습니다. 
두 가지 경우에 대해 만들었습니다. 
내용이 모두 텍스트라 시맨틱 태그가 고민되는 것 같아요 ! 별로면 편하게 추천해주세요 :)

Feat(client): onboarding title component 구현

---

apps/client/src/pages/onboarding/onboarding-page.tsx
apps/client/src/shared/api/domain/onboarding/queries.ts
apps/client/src/widgets/onboarding/components/step/matching-loader/matching-loader.tsx
apps/client/src/widgets/onboarding/components/step/start-content/start-content.tsx
apps/client/src/widgets/onboarding/mocks/user-info.mock.ts

- close #227 
- 온보딩 페이지 start와 matching 페이지에서 nickname 불러오기
- 이름을 입력하기 전이므로! 온보딩에서는 nickname을 불러오기로 하였습니다 (기획과 의논 O)
- mock data 삭제

Feat(client): 정보 입력 페이지 유저 정보 조회 api 연동

---

apps/client/src/pages/report/report-page.tsx
apps/client/src/shared/types/schema.d.ts
apps/client/src/widgets/report/components/summarize/summarize.tsx

- close #232 
- schema.d.ts 파일 자동 생성
- nickname을 username으로 변경
- username(본명)
- nickname(별명)

Chore(client): 보험 추천 리포트 username 본명으로 변경

---

apps/client/src/pages/login-fallback/login-fallback-page.tsx

- close #238
- 로그인 리다이렉트 문제 해결

HOTFIX: 로그인 리다이렉트 문제 해결

---

apps/client/src/pages/home/home-page.css.ts
apps/client/src/pages/home/home-page.tsx
apps/client/src/shared/router/routes/global-routes.tsx
apps/client/src/shared/router/routes/layout-free-routes.tsx
apps/client/src/widgets/home/components/features-section/features-section.css.ts
apps/client/src/widgets/home/components/features-section/features-section.tsx
apps/client/src/widgets/home/components/info-section/info-section.css.ts
apps/client/src/widgets/home/components/info-section/info-section.tsx
apps/client/src/widgets/home/components/info-section/recommended-info-section.tsx

> - #251
- 보험 추천을 받지 않은 페이지에서 이전에 lazy 적용하면서 생겼던 문제와 연결되는 스타일 문제를 해결했습니다.
[fix: 보험추천 받지 않은 Infosection chip 에 패딩 위치 옮기기](https://github.com/team-bofit/bofit-client/commit/84d675de221fea9f1d400b92844d22985a0c7417)
- infoSection 에서 내 보험 추천 받기 누르면 navigate 되도록 수정 
[feat: infoSection 에서 버튼 누르면 navigate](https://github.com/team-bofit/bofit-client/commit/fce5525ba7e7e55f14b6b59a7534c0617737dc80)
- 고객님님을 고객님으로 수정 
[fix: 고객님님 -> 고객님](https://github.com/team-bofit/bofit-client/pull/253/commits/7c1ee98d9509088fcaeb8c19fd24e0e81c667546)

Fix(client): home 에서 버그를 해결합니다. 

---

apps/client/src/pages/home/home-page.tsx
apps/client/src/shared/configs/app-config.ts

> - #258
인증 기능 활성화 했습니다. 
이제 ProtectedRoute 는 로그인 없이 접근 불가능합니다!

Feat(client): 인증 기능 활성화 

---

apps/client/src/widgets/report/components/accordion/accordion.css.ts
apps/client/src/widgets/report/components/accordion/accordion.tsx

- close #257 
- iconContainer recipe variants 사용 대신, icon 자체에 rotate props 설정
https://github.com/user-attachments/assets/04e58d5d-b594-4727-913b-44dd93a08c41

Refactor(client): accordion 컴포넌트 icon 회전 방향 수정

---

apps/client/src/shared/router/routes/protected-route.tsx
apps/client/src/shared/types/schema.d.ts
apps/client/src/widgets/report/components/report-detail/report-detail.tsx

> 관련 있는 Issue를 태그해주세요. (e.g. > - #100)
_해당 PR에 대한 작업 내용을 요약하여 작성해주세요._
- _해당 PR에 수행한 작업을 작성해주세요._

Fix(client): QA 시작 전 수정

---

apps/client/src/widgets/mypage/body.tsx
apps/client/src/widgets/onboarding/components/insurance-notice-modal/insurance-notice-modal.tsx
apps/client/src/widgets/report/components/recommend/recommend.css.ts
apps/client/src/widgets/report/components/recommend/recommend.tsx

- close #271 
- https://www.notion.so/16px-234d31201173809c8dd5ff98e4b2c5df?source=copy_link
- https://www.notion.so/234d3120117381408d23ed773cc9329f?source=copy_link
- https://www.notion.so/234d3120117380e787bcc6d5a3ea31f1?source=copy_link

QA-1: 스타일 수정

---

apps/client/index.html

> - #284 
- 기존 설계에 따라 모바일 키패드에서 엔터를 done으로 바꿨으나 요청에 의해 다시 바꿉니다.
- https://www.notion.so/234d3120117380ddaf25eccd88b8f9c5?source=copy_link

QA-1: 모바일 엔터키 done을 엔터로 수정

---

apps/client/src/pages/my/my-page.tsx
apps/client/src/widgets/home/components/info-section/info-section.tsx
apps/client/src/widgets/mypage/body.tsx

- close #285 
- https://www.notion.so/_-X-234d31201173800cbc1de9dd1ac4c713?source=copy_link
- https://www.notion.so/CTA-_-_-234d3120117380b2a584e742d0760842?source=copy_link
- https://www.notion.so/234d312011738020859ccaec5c78b547?source=copy_link
- https://www.notion.so/error-page-_-234d3120117380bc82a1e9eb4f8a29d8?source=copy_link

QA-1: 리포트 없을 시, 마이페이지 화면 다르게

---

apps/client/src/widgets/home/components/info-section/recommended-info-section.tsx
apps/client/src/widgets/home/components/tip/tip.css.ts
packages/bds-ui/src/components/chip/chip.tsx

> -#288
[fix: chip type extents](https://github.com/team-bofit/bofit-client/commit/8565a641fdccd9e32a76633a677030567931586d)
[feat: chip cursor 제거](https://github.com/team-bofit/bofit-client/commit/c8a9d86d185f47922d355c2dfbd14c9ea1c009f8)
[feat: 보험팁 커서 제거](https://github.com/team-bofit/bofit-client/commit/517c112db5f907379fea4893ea63135d17058862)

QA-1: home 페이지 chip type extends , cursor 제거

---

apps/client/src/widgets/report/components/report-detail/report-detail.tsx
apps/client/src/widgets/report/constant/section-component-constant.ts
apps/client/src/widgets/report/constant/tab-constant.ts
apps/client/src/widgets/report/hooks/tab-sync.tsx
apps/client/src/widgets/report/hooks/use-move-scroll.tsx
packages/bds-ui/src/components/tab/tab.css.ts
packages/bds-ui/src/components/tab/tab.tsx

- #282
보험 추천 리포트 페이지 스크롤시 자동 Tab을 선택합니다.
보험 추천 리포트 페이지 스크롤시 자동 Tab 선택
https://github.com/user-attachments/assets/c3d08d0f-dad0-4bac-8ea3-c8185a7e2375

QA-1: 보험 추천 리포트 페이지 스크롤시 자동 Tab 선택

---

apps/client/src/widgets/onboarding/components/insurance-notice-modal/insurance-notice-modal.css.ts
apps/client/src/widgets/onboarding/components/insurance-notice-modal/insurance-notice-modal.tsx
packages/bds-ui/src/components/modal/modal.css.ts
packages/bds-ui/src/components/modal/modal.tsx

- close #299 
- https://www.notion.so/active-234d3120117380e9a8fef800a4c1fa3e?source=copy_link

feat: 글씨 눌렀을 떄도 checkbox 체크

---

apps/client/src/pages/community/community-detail/community-detail.css.ts
apps/client/src/pages/community/community-detail/community-detail.tsx
apps/client/src/pages/community/community-page.css.ts
apps/client/src/pages/community/community-page.tsx

HOFIX: 커뮤니티 디테일 페이지 스타일 수정

---

apps/client/index.html

Feat(client): 모바일 확대방지

---

apps/client/src/pages/onboarding/onboarding-page.tsx

- #323 
- 기존 유저 info 조회에서 받은 값으로 navigate 를 분기처리합니다

Feat(client): onboarding url 방어

---

README.md

> close #326  
_해당 PR에 대한 작업 내용을 요약하여 작성해주세요._
- Frontend Developer 사진 추가 및 계정 하이퍼링크 연결
- 이전 사진은 밑으로 이동했습니다 (아까움 이슈)

Chore(project): README 최신화

---

apps/client/src/pages/my/my-page.tsx

- #350 
- 마이 페이지 navigate 버튼의 로직을 수정했습니다
우선 report 페이지로 리다이렉트 되어야 하는데 경로자체가 잘못 되어있었군요. 뿐만 아니라 삼항 연산자의 순서도 반대로 되어있어서 디스코드에 qa 가 접수되었어요 
이 부분 수정합니다

Fix(client): 마이페이지 navigate 버튼 로직 수정 

---

.changeset/ninety-spoons-unite.md

> - #355
- _해당 PR에 수행한 작업을 작성해주세요._
change set 세팅 테스트와 함께 첫 메이저 버전 컨트롤 PR 입니다.

Version-Contol(v.0.0.0)

---

.changeset/breezy-windows-cry.md

> - #374 
_해당 PR에 대한 작업 내용을 요약하여 작성해주세요._

Version-Contol(v._)
